### ISSUE TITLE
Returns wrong sentiment for PHP 7

### ISSUE THREAD

**Issue by sameerpanjwani** [AntoineAugusti/laravel-sentiment-analysis#11]
This package used to work up well till we had PHP 5.6 but after we upgraded to PHP 7, phrases that were "neutral" are being returned as "positive". Not sure why? 

All possible neutral phrases like:
"sample test line"
"maths in science"
"men and women in a line"

Any ideas

**Comment by AntoineAugusti** [comment]
Sorry, no idea coming out. I don't use this package in production. As this is just a wrapper for https://github.com/JWHennessey/phpInsight, maybe you can report it there? If you manage to find the issue please share it.

**Comment by JPeterson2015** [comment]
update sentiment.php to 

`private $prior = array(
		'pos' => 0.333,
		'neg' => 0.333,
		'neu' => 0.334
	);`
