### ISSUE TITLE
SentimentAnalysis::score() does not do what it says

### ISSUE THREAD

**Issue by zethon** [AntoineAugusti/laravel-sentiment-analysis#12]
Like a lot of API, this library computes the "chances" of the statement being positive, neutral and negative. For example, `scores()` can return:

`@example ['negative' => 0.5, 'neutral' => 0.25, 'positive' => 0.25]`

So, you would expect the `score()` function in this case to be less than 0.5 (ie. negative). It says:

```
    /**
     * Get the confidence of a decision for a result. The closer to 1, the better.
     *
     * @param string $string The given sentence
     *
     * @return float The confidence of a decision for a result. The close to 1, the better
     */
```
However looking at the code:

```
    public function score($string)
    {
        $scores = $this->scores($string);
        return max($scores);
    }
```

one can see that this will simply return 0.5, suggesting the score is "neutral".

**Comment by AntoineAugusti** [comment]
Hey,

For me it does what it says. It is supposed to give **the confidence of a decision for a result.** You can therefore use the score to determine if the classification is reliable enough for you. You can have a confidence threshold (maybe `0.7`?) under which you will not take any decision, and above it you will take into account the classification.

Is it better?

**Comment by zethon** [comment]
I guess I misunderstood the comments. Thanks for the clarification.
