### ISSUE TITLE
Call to undefined method Illuminate\Foundation\Application::share()

### ISSUE THREAD

**Issue by Gichure** [AntoineAugusti/laravel-sentiment-analysis#14]
Getting this error on Laravel 5.4

FatalThrowableError in LaravelSentimentAnalysisServiceProvider.php line 16: Call to undefined method Illuminate\Foundation\Application::share() and version 2.1 of the wrapper

**Comment by vmitchell85** [comment]
PR #13 should take care of this.

@AntoineAugusti Any way we can get this merged soon? Thanks a ton for your work on this package!

**Comment by AntoineAugusti** [comment]
Just merged the PR and released a new version with the changes. Thanks

**Comment by vmitchell85** [comment]
Thanks!
