### ISSUE TITLE
Adding new dataset

### ISSUE THREAD

**Issue by Malina-Shrestha** [AntoineAugusti/laravel-sentiment-analysis#18]
how to add new word in dataset ?

**Comment by AntoineAugusti** [comment]
Hello,

The class provides a way to inject a data folder through the constructor: https://github.com/AntoineAugusti/laravel-sentiment-analysis/blob/636d07b333043a7a5716b034f1e0bfabfe8368b7/src/SentimentAnalysis.php#L23-L26 If you provide a custom folder, you can override some of the default files from phpInsight: https://github.com/JWHennessey/phpInsight/tree/master/lib/PHPInsight. Take a look at the `data` folder and the `PHPInsight \Sentiment` class.

**Comment by Malina-Shrestha** [comment]
Thank you for responding my email. Actually the problem was I used
phpinsight in my college project for analyzing product reviews, and the
mixed reviews such as "The product is nice but could have been more better
or the product is prolly good but lacks consistency " is considered as
positive but it should be analysed as neutral. I am unable to fix this
problem. Could you please provide me some ideas. It would be a great help.

**Comment by AntoineAugusti** [comment]
You'll likely want to look at machine learning / deep learning techniques. Worth a read: https://scikit-learn.org/stable/tutorial/text_analytics/working_with_text_data.html
