### ISSUE TITLE
Please help me run it

### ISSUE THREAD

**Issue by sajjad566** [AntoineAugusti/laravel-sentiment-analysis#19]
I've installed the package updated the composer. but cant seem to run it on my controller.
Can u please give me exact line of code to how check a statement.
because when I run SentimentAnalysis::decision($sentence); , it gives me error(Non-static method Antoineaugusti\LaravelSentimentAnalysis\SentimentAnalysis::decision() should not be called statically).
Please reply ASAP. I really need it. Thanks

**Comment by AntoineAugusti** [comment]
Hello,

You can't ask an open source maintainer to reply "ASAP".
