### ISSUE TITLE
I revived this problem while trying to install the package using composer require

### ISSUE THREAD

**Issue by mohamadabdelhady** [AntoineAugusti/laravel-sentiment-analysis#26]
Problem 1
    - Root composer.json requires antoineaugusti/laravel-sentiment-analysis ^4.0 -> satisfiable by antoineaugusti/laravel-sentiment-analysis[v4.0].
    - antoineaugusti/laravel-sentiment-analysis v4.0 requires illuminate/support ^6 || ^7 -> found illuminate/support[v6.0.0, ..., 6.x-dev, v7.0.0, ..., 7.x-dev] but these were not loaded, likely because it conflicts with another require.

**Comment by muhammad-Ali-Nawaz** [comment]
Facing same issue :(

**Comment by AntoineAugusti** [comment]
Fixed by https://github.com/AntoineAugusti/laravel-sentiment-analysis/pull/27, use v4.1
