### ISSUE TITLE
Custom Dictionaries

### ISSUE THREAD

**Issue by simondotwhite** [AntoineAugusti/laravel-sentiment-analysis#4]
Hey,

Is it possible to set custom dictionaries? 

I'm happy enough to create a pull request if there isn't.

**Comment by AntoineAugusti** [comment]
@Sekonda Hey, this is a wrapper for another library. I guess you could send a PR to add / change [these files](https://github.com/JWHennessey/phpInsight/tree/master/lib/PHPInsight/dictionaries)

**Comment by simondotwhite** [comment]
@AntoineAugusti I know it's a wrapper, but [your constructor](https://github.com/AntoineAugusti/laravel-sentiment-analysis/blob/master/src/SentimentAnalysis.php#L18) differs to the [phpInsight constructor](https://github.com/JWHennessey/phpInsight/blob/master/lib/PHPInsight/Sentiment.php#L117). 

Even if the constructor remains the same and there was a method to expose the [setDataFolder](https://github.com/JWHennessey/phpInsight/blob/master/lib/PHPInsight/Sentiment.php#L259) method from phpinsight.

**Comment by AntoineAugusti** [comment]
@Sekonda Right, in that case a PR would be awesome!

Please update the README, docblocks and add tests 👍 👏

**Comment by simondotwhite** [comment]
@AntoineAugusti I've created the [pull request](https://github.com/AntoineAugusti/laravel-sentiment-analysis/pull/5). This is my first pull request, so I think I've done it correctly. 

I was testing on PHP7 on my machine and everything passed but travis has them failing on older versions of PHP.

**Comment by AntoineAugusti** [comment]
Done in https://github.com/AntoineAugusti/laravel-sentiment-analysis/pull/5

**Comment by AntoineAugusti** [comment]
@Sekonda I've just published a new version https://github.com/AntoineAugusti/laravel-sentiment-analysis/releases.

Congrats on your first PR! If you've got time to backport this to Laravel 4, that'd awesome ;)

**Comment by simondotwhite** [comment]
Thanks for your help! 

I'll get another PR for Laravel 4 in later today/tonight as I need it for an older codebase.
