### ISSUE TITLE
Backport Custom Dictionaries

### ISSUE THREAD

**Issue by simondotwhite** [AntoineAugusti/laravel-sentiment-analysis#7]
Hey @AntoineAugusti I'm not really sure how I go about merging into a tag/release. 

I've back ported the changes into my fork on a [v.1.1.2 branch](https://github.com/Sekonda/laravel-sentiment-analysis/tree/v1.1.2) and [tagged the release](https://github.com/Sekonda/laravel-sentiment-analysis/releases/tag/v1.1.2).

Do you have to create a branch in this repo and I can create pull request for it and then tag the release?

**Comment by AntoineAugusti** [comment]
Hey @Sekonda, can you make a PR against the `laravel-4` branch I just created from the v1.1.1 tag? I'll then merge it then tag a v1.2 release ;)

Edit: did it https://github.com/AntoineAugusti/laravel-sentiment-analysis/pull/8

**Comment by AntoineAugusti** [comment]
should be good 👍 https://github.com/AntoineAugusti/laravel-sentiment-analysis/releases/tag/v1.2
